build-package new release: dom 30 mar 2025 13:37:12 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/pkgbuild/pkgbuild.install b/pkgbuild/pkgbuild.install
--- a/pkgbuild/pkgbuild.install
+++ b/pkgbuild/pkgbuild.install
@@ -29,6 +29,7 @@ export DOTPREFIX="  ${black}::${reset} "
 export bold="\033[1m"
 export reset="\033[0m"
 declare IS_UPGRADE=false
+declare IS_DBLOCK=false
 declare DM='lightdm'
 declare WM='gnome'
 declare pkgname=chili-"${WM}"
@@ -64,39 +65,41 @@ sh_load_optdepends() {
 }
 
 sh_restoring_lock() {
-	msg "Restauring pacman lock: /var/lib/pacman/db.lck"
-	touch /var/lib/pacman/db.lck &>/dev/null
+	if $IS_DBLOCK; then
+		msg "Restauring pacman lock: /var/lib/pacman/db.lck"
+		touch /var/lib/pacman/db.lck &>/dev/null
+	fi
 }
 
 sh_check_package_exist() {
-  local pkg
-  local not_installed=()
-  local not_found=()
+	local pkg
+	local not_installed=()
+	local not_found=()
 
-  # Verifica pacotes instalados localmente de uma vez
-  for pkg in "${OPTDEPENDS[@]}"; do
-    if ! pacman -Qq "$pkg" &>/dev/null; then
-      not_installed+=("$pkg")
-    fi
-  done
+	# Verifica pacotes instalados localmente de uma vez
+	for pkg in "${OPTDEPENDS[@]}"; do
+		if ! pacman -Qq "$pkg" &>/dev/null; then
+			not_installed+=("$pkg")
+		fi
+	done
 
-  # Verifica pacotes ausentes no repositório de uma vez
-  if ((${#not_installed[@]})); then
-    for pkg in "${not_installed[@]}"; do
-      if ! pacman -Ssq "^$pkg$" &>/dev/null; then
-        not_found+=("$pkg")
-      fi
-    done
-  fi
+	# Verifica pacotes ausentes no repositório de uma vez
+	if ((${#not_installed[@]})); then
+		for pkg in "${not_installed[@]}"; do
+			if ! pacman -Ssq "^$pkg$" &>/dev/null; then
+				not_found+=("$pkg")
+			fi
+		done
+	fi
 
-  # Se houver pacotes não encontrados, exibe erro
-  if ((${#not_found[@]})); then
-    die "Fatal: os seguintes pacotes não existem no repositório: ${not_found[*]}"
-  fi
+	# Se houver pacotes não encontrados, exibe erro
+	if ((${#not_found[@]})); then
+		die "Fatal: os seguintes pacotes não existem no repositório: ${not_found[*]}"
+	fi
 
-  for pkg in "${OPTDEPENDS[@]}"; do
-    log_ok "Check: ${cyan}$pkg"
-  done
+	for pkg in "${OPTDEPENDS[@]}"; do
+		log_ok "Check: ${cyan}$pkg"
+	done
 }
 
 sh_start_dbus_in_chroot() {
@@ -116,28 +119,28 @@ sh_start_dbus_in_chroot() {
 }
 
 sh_copy_user_etc_usr_opt_files() {
-  msg "Configuring the package after installation/upgrade..."
+	msg "Configuring the package after installation/upgrade..."
 
-  # Copiar a estrutura para os diretórios de destino
-  local dirs=("usr" "etc" "opt")
+	# Copiar a estrutura para os diretórios de destino
+	local dirs=("usr" "etc" "opt")
 
-  for dir in "${dirs[@]}"; do
-    if [ -d "/usr/share/${pkgname}/${dir}" ]; then
-      # Copiar os arquivos e subdiretórios de /usr/share/${pkgname}/${dir} para o sistema
-      cp -a "/usr/share/${pkgname}/${dir}" "/"
-    fi
-  done
-  # Sobrescreve o arquivo plymouthd.conf com a versão do pacote
-  #cp -af /usr/lib/manjaro-tools/util-live.sh /usr/lib/manjaro-tools/util-live.sh.pacnew
-  #cp -af /usr/lib/manjaro-tools/util-live.sh.community /usr/lib/manjaro-tools/util-live.sh
-  #cp -af /usr/share/${pkgname}/usr/lib/manjaro-tools/util-live.sh.community /usr/lib/manjaro-tools/util-live.sh
-  #chmod +x /usr/lib/manjaro-tools/util-live.sh
+	for dir in "${dirs[@]}"; do
+		if [ -d "/usr/share/${pkgname}/${dir}" ]; then
+			# Copiar os arquivos e subdiretórios de /usr/share/${pkgname}/${dir} para o sistema
+			cp -a "/usr/share/${pkgname}/${dir}" "/"
+		fi
+	done
+	# Sobrescreve o arquivo plymouthd.conf com a versão do pacote
+	#cp -af /usr/lib/manjaro-tools/util-live.sh /usr/lib/manjaro-tools/util-live.sh.pacnew
+	#cp -af /usr/lib/manjaro-tools/util-live.sh.community /usr/lib/manjaro-tools/util-live.sh
+	#cp -af /usr/share/${pkgname}/usr/lib/manjaro-tools/util-live.sh.community /usr/lib/manjaro-tools/util-live.sh
+	#chmod +x /usr/lib/manjaro-tools/util-live.sh
 }
 
 post_install() {
 	msg "Initializing system installation and configuration..."
 
-  sh_copy_user_etc_usr_opt_files
+	sh_copy_user_etc_usr_opt_files
 	sh_load_optdepends
 
 	[[ -e /etc/environment ]] && source /etc/environment
@@ -150,6 +153,7 @@ post_install() {
 	fi
 
 	if [[ -f /var/lib/pacman/db.lck ]]; then
+		IS_DBLOCK=true
 		msg "Removing pacman lock: /var/lib/pacman/db.lck"
 		rm -f /var/lib/pacman/db.lck &>/dev/null
 	fi
@@ -168,17 +172,24 @@ post_install() {
 	}
 
 	install_packages() {
-		pacman -S --quiet --noconfirm --needed --overwrite \* "$@" &>/dev/null
+		# Captura o erro do pacman
+		if ! pacman -S --quiet --noconfirm --needed --overwrite \* "$@" >/tmp/${pkgname}-pacman_output_log 2>/tmp/${pkgname}-pacman_error_log; then
+			die "$(</tmp/${pkgname}-pacman_error_log)"
+		fi
+		# Se não houver erro (ou erro de já estar instalado/atualizado)
+		rm /tmp/${pkgname}-pacman_error_log &>/dev/null
+		rm /tmp/${pkgname}-pacman_output_log &>/dev/null
+		return 0
 	}
 
-	msg "Please wait, synchronizing databases..."
-	synchronizing_database
+	#	msg "Please wait, synchronizing databases..."
+	#	synchronizing_database
 
 	msg "Installing common packages: ${COMMON_PACKAGES[*]}"
 	install_packages "${COMMON_PACKAGES[@]}"
 
-	msg "Checking for the existence of packages..."
-	sh_check_package_exist
+	#	msg "Checking for the existence of packages..."
+	#	sh_check_package_exist
 
 	msg "Installing optdepends packages: ${OPTDEPENDS[*]}"
 	install_packages "${OPTDEPENDS[@]}"
@@ -197,10 +208,10 @@ post_install() {
 		msg "Installing NVIDIA packages: $KERNEL_PACKAGE nvidia-utils nvidia-settings"
 		install_packages "$KERNEL_PACKAGE" nvidia-utils nvidia-settings
 
-    msg "Blacklisting Nouveau..."
-    mkdir -p /etc/modprobe.d/ &>/dev/null
-    echo -e "blacklist nouveau\ninstall nouveau /bin/true" >/etc/modprobe.d/nouveau.conf
-    echo -e "blacklist nouveau\ninstall nouveau /bin/true" >/etc/modprobe.d/blacklist.conf
+		msg "Blacklisting Nouveau..."
+		mkdir -p /etc/modprobe.d/ &>/dev/null
+		echo -e "blacklist nouveau\ninstall nouveau /bin/true" >/etc/modprobe.d/nouveau.conf
+		echo -e "blacklist nouveau\ninstall nouveau /bin/true" >/etc/modprobe.d/blacklist.conf
 	elif grep -qiw "Intel" <<<"$GPU_INFO"; then
 		msg "Intel GPU detected! Installing drivers..."
 		install_packages vulkan-intel lib32-vulkan-intel
